// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomeDocumentDataSlicesSlice =
  | ContactSlice
  | FaqsSlice
  | OurRecentProjectsSlice
  | OurClientsSlice
  | OurBrandSlice
  | HistorySlice
  | ScoreSlice
  | HeroSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: Home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: Home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: Home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: Home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `Home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "Home", Lang>;

/**
 * Item in *Footer → Footer Media*
 */
export interface FooterDocumentDataFooterMediaItem {
  /**
   * Logo field in *Footer → Footer Media*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footer_media[].Logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  Logo: prismic.ImageField<never>;
}

/**
 * Item in *Footer → Footer Link 1*
 */
export interface FooterDocumentDataFooterLink1Item {
  /**
   * Href field in *Footer → Footer Link 1*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.FooterLink1[].Href
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  Href: prismic.LinkField;

  /**
   * Label  field in *Footer → Footer Link 1*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.FooterLink1[].Label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  Label: prismic.RichTextField;
}

/**
 * Item in *Footer → Footer Link 2*
 */
export interface FooterDocumentDataFooterLink2Item {
  /**
   * Href field in *Footer → Footer Link 2*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.FooterLink2[].Href
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  Href: prismic.LinkField;

  /**
   * Label  field in *Footer → Footer Link 2*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.FooterLink2[].Label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  Label: prismic.RichTextField;
}

/**
 * Item in *Footer → Footer Link 3*
 */
export interface FooterDocumentDataFooterLink3Item {
  /**
   * Href field in *Footer → Footer Link 3*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.FooterLink3[].Href
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  Href: prismic.LinkField;

  /**
   * Label  field in *Footer → Footer Link 3*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.FooterLink3[].Label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  Label: prismic.RichTextField;
}

/**
 * Item in *Footer → Footer Link 4*
 */
export interface FooterDocumentDataFooterLink4Item {
  /**
   * Href field in *Footer → Footer Link 4*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.FooterLink4[].Href
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  Href: prismic.LinkField;

  /**
   * Label  field in *Footer → Footer Link 4*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.FooterLink4[].Label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  Label: prismic.RichTextField;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Footer Logo field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.FooterLogo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  FooterLogo: prismic.ImageField<never>;

  /**
   * Heading field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.Heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  Heading: prismic.RichTextField;

  /**
   * Title field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.Title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  Title: prismic.RichTextField;

  /**
   * Sub Title field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.SubTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  SubTitle: prismic.KeyTextField;

  /**
   * Description field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.Description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  Description: prismic.KeyTextField;

  /**
   * Footer Media field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footer_media[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  footer_media: prismic.GroupField<Simplify<FooterDocumentDataFooterMediaItem>>;

  /**
   * Footer Link 1 field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.FooterLink1[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  FooterLink1: prismic.GroupField<Simplify<FooterDocumentDataFooterLink1Item>>;

  /**
   * Footer Link 2 field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.FooterLink2[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  FooterLink2: prismic.GroupField<Simplify<FooterDocumentDataFooterLink2Item>>;

  /**
   * Footer Link 3 field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.FooterLink3[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  FooterLink3: prismic.GroupField<Simplify<FooterDocumentDataFooterLink3Item>>;

  /**
   * Footer Link 4 field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.FooterLink4[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  FooterLink4: prismic.GroupField<Simplify<FooterDocumentDataFooterLink4Item>>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

/**
 * Item in *Navbar → Menus *
 */
export interface NavbarDocumentDataMenusItem {
  /**
   * Label field in *Navbar → Menus *
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.Menus[].Label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  Label: prismic.KeyTextField;

  /**
   * Href field in *Navbar → Menus *
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.Menus[].Href
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  Href: prismic.LinkField;
}

/**
 * Content for Navbar documents
 */
interface NavbarDocumentData {
  /**
   * Navbar Logo field in *Navbar*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.NavbarLogo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  NavbarLogo: prismic.ImageField<never>;

  /**
   * Heading field in *Navbar*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.Heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  Heading: prismic.RichTextField;

  /**
   * Menus  field in *Navbar*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.Menus[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  Menus: prismic.GroupField<Simplify<NavbarDocumentDataMenusItem>>;

  /**
   * Button field in *Navbar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.Button
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  Button: prismic.KeyTextField;
}

/**
 * Navbar document from Prismic
 *
 * - **API ID**: `navbar`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavbarDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavbarDocumentData>,
    "navbar",
    Lang
  >;

/**
 * Item in *Top Navbar  → TopNavbar*
 */
export interface TopNavbarDocumentDataTopNavbarItem {
  /**
   * Href field in *Top Navbar  → TopNavbar*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: top_navbar.TopNavbar[].Href
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  Href: prismic.LinkField;

  /**
   * Label  field in *Top Navbar  → TopNavbar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: top_navbar.TopNavbar[].Label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  Label: prismic.KeyTextField;
}

/**
 * Content for Top Navbar  documents
 */
interface TopNavbarDocumentData {
  /**
   * TopNavbar field in *Top Navbar *
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: top_navbar.TopNavbar[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  TopNavbar: prismic.GroupField<Simplify<TopNavbarDocumentDataTopNavbarItem>>;
}

/**
 * Top Navbar  document from Prismic
 *
 * - **API ID**: `top_navbar`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TopNavbarDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<TopNavbarDocumentData>,
    "top_navbar",
    Lang
  >;

export type AllDocumentTypes =
  | HomeDocument
  | FooterDocument
  | NavbarDocument
  | TopNavbarDocument;

/**
 * Item in *Contact → Default → Primary → Contact Form*
 */
export interface ContactSliceDefaultPrimaryContactFormItem {
  /**
   * Label  field in *Contact → Default → Primary → Contact Form*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.ContactForm[].Label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  Label: prismic.KeyTextField;

  /**
   * Type field in *Contact → Default → Primary → Contact Form*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.ContactForm[].Type
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  Type: prismic.KeyTextField;

  /**
   * Placeholder field in *Contact → Default → Primary → Contact Form*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.ContactForm[].Placeholder
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  Placeholder: prismic.KeyTextField;
}

/**
 * Item in *Contact → Default → Primary → Button*
 */
export interface ContactSliceDefaultPrimaryButtonItem {
  /**
   * Href field in *Contact → Default → Primary → Button*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.Button[].Href
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  Href: prismic.LinkField;

  /**
   * Text field in *Contact → Default → Primary → Button*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.Button[].Text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  Text: prismic.KeyTextField;
}

/**
 * Primary content in *Contact → Default → Primary*
 */
export interface ContactSliceDefaultPrimary {
  /**
   * Contact Image field in *Contact → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.ContactImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  ContactImage: prismic.ImageField<never>;

  /**
   * Heading field in *Contact → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.Heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  Heading: prismic.RichTextField;

  /**
   * Sub Heading field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.SubHeading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  SubHeading: prismic.KeyTextField;

  /**
   * Contact Form field in *Contact → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.ContactForm[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  ContactForm: prismic.GroupField<
    Simplify<ContactSliceDefaultPrimaryContactFormItem>
  >;

  /**
   * Button field in *Contact → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.Button[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  Button: prismic.GroupField<Simplify<ContactSliceDefaultPrimaryButtonItem>>;
}

/**
 * Default variation for Contact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Contact*
 */
type ContactSliceVariation = ContactSliceDefault;

/**
 * Contact Shared Slice
 *
 * - **API ID**: `contact`
 * - **Description**: Contact
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSlice = prismic.SharedSlice<
  "contact",
  ContactSliceVariation
>;

/**
 * Item in *Faqs → Default → Primary → Content*
 */
export interface FaqsSliceDefaultPrimaryContentItem {
  /**
   * Title field in *Faqs → Default → Primary → Content*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.Content[].Title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  Title: prismic.RichTextField;

  /**
   * Sub Title field in *Faqs → Default → Primary → Content*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.Content[].SubTitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  SubTitle: prismic.KeyTextField;
}

/**
 * Primary content in *Faqs → Default → Primary*
 */
export interface FaqsSliceDefaultPrimary {
  /**
   * Heading field in *Faqs → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.Heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  Heading: prismic.RichTextField;

  /**
   * Sub Icon field in *Faqs → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.SubIcon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  SubIcon: prismic.ImageField<never>;

  /**
   * Add Icon field in *Faqs → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.AddIcon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  AddIcon: prismic.ImageField<never>;

  /**
   * Sub Heading field in *Faqs → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.SubHeading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  SubHeading: prismic.KeyTextField;

  /**
   * Content field in *Faqs → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.Content[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  Content: prismic.GroupField<Simplify<FaqsSliceDefaultPrimaryContentItem>>;
}

/**
 * Default variation for Faqs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Faqs*
 */
type FaqsSliceVariation = FaqsSliceDefault;

/**
 * Faqs Shared Slice
 *
 * - **API ID**: `faqs`
 * - **Description**: Faqs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqsSlice = prismic.SharedSlice<"faqs", FaqsSliceVariation>;

/**
 * Item in *Hero → Default → Primary → Button*
 */
export interface HeroSliceDefaultPrimaryButtonItem {
  /**
   * Label  field in *Hero → Default → Primary → Button*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.Button[].Label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  Label: prismic.KeyTextField;

  /**
   * Button Link field in *Hero → Default → Primary → Button*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.Button[].ButtonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  ButtonLink: prismic.LinkField;
}

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Background Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.BackgroundImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  BackgroundImage: prismic.ImageField<never>;

  /**
   * Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.Heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  Heading: prismic.KeyTextField;

  /**
   * Description field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.Description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  Description: prismic.RichTextField;

  /**
   * Button field in *Hero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.Button[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  Button: prismic.GroupField<Simplify<HeroSliceDefaultPrimaryButtonItem>>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *History → Default → Primary*
 */
export interface HistorySliceDefaultPrimary {
  /**
   * Background Image field in *History → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: history.default.primary.BackgroundImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  BackgroundImage: prismic.ImageField<never>;

  /**
   * Title field in *History → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: history.default.primary.Title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  Title: prismic.RichTextField;

  /**
   * Description field in *History → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: history.default.primary.Description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  Description: prismic.RichTextField;
}

/**
 * Default variation for History Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HistorySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HistorySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *History*
 */
type HistorySliceVariation = HistorySliceDefault;

/**
 * History Shared Slice
 *
 * - **API ID**: `history`
 * - **Description**: History
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HistorySlice = prismic.SharedSlice<
  "history",
  HistorySliceVariation
>;

/**
 * Primary content in *OurBrand → Default → Primary*
 */
export interface OurBrandSliceDefaultPrimary {
  /**
   * Title field in *OurBrand → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_brand.default.primary.Title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  Title: prismic.RichTextField;

  /**
   * Description field in *OurBrand → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_brand.default.primary.Description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  Description: prismic.RichTextField;

  /**
   * Background Image field in *OurBrand → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: our_brand.default.primary.BackgroundImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  BackgroundImage: prismic.ImageField<never>;
}

/**
 * Default variation for OurBrand Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurBrandSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OurBrandSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *OurBrand*
 */
type OurBrandSliceVariation = OurBrandSliceDefault;

/**
 * OurBrand Shared Slice
 *
 * - **API ID**: `our_brand`
 * - **Description**: OurBrand
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurBrandSlice = prismic.SharedSlice<
  "our_brand",
  OurBrandSliceVariation
>;

/**
 * Item in *OurClients → Default → Primary → Our Clients*
 */
export interface OurClientsSliceDefaultPrimaryOurClientsItem {
  /**
   * Profile Image field in *OurClients → Default → Primary → Our Clients*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: our_clients.default.primary.OurClients[].ProfileImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  ProfileImage: prismic.ImageField<never>;

  /**
   * Name field in *OurClients → Default → Primary → Our Clients*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_clients.default.primary.OurClients[].Name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  Name: prismic.RichTextField;

  /**
   * Occupation field in *OurClients → Default → Primary → Our Clients*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_clients.default.primary.OurClients[].Occupation
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  Occupation: prismic.RichTextField;

  /**
   * Stars field in *OurClients → Default → Primary → Our Clients*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: our_clients.default.primary.OurClients[].Stars
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  Stars: prismic.ImageField<never>;

  /**
   * Description field in *OurClients → Default → Primary → Our Clients*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_clients.default.primary.OurClients[].Description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  Description: prismic.RichTextField;
}

/**
 * Primary content in *OurClients → Default → Primary*
 */
export interface OurClientsSliceDefaultPrimary {
  /**
   * Title field in *OurClients → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_clients.default.primary.Title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  Title: prismic.RichTextField;

  /**
   * Our Clients field in *OurClients → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: our_clients.default.primary.OurClients[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  OurClients: prismic.GroupField<
    Simplify<OurClientsSliceDefaultPrimaryOurClientsItem>
  >;
}

/**
 * Default variation for OurClients Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurClientsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OurClientsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *OurClients*
 */
type OurClientsSliceVariation = OurClientsSliceDefault;

/**
 * OurClients Shared Slice
 *
 * - **API ID**: `our_clients`
 * - **Description**: OurClients
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurClientsSlice = prismic.SharedSlice<
  "our_clients",
  OurClientsSliceVariation
>;

/**
 * Item in *OurRecentProjects → Default → Primary → Card*
 */
export interface OurRecentProjectsSliceDefaultPrimaryCardItem {
  /**
   * Cover Image field in *OurRecentProjects → Default → Primary → Card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: our_recent_projects.default.primary.Card[].CoverImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  CoverImage: prismic.ImageField<never>;

  /**
   * Heading field in *OurRecentProjects → Default → Primary → Card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_recent_projects.default.primary.Card[].Heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  Heading: prismic.RichTextField;

  /**
   * Sub Heading field in *OurRecentProjects → Default → Primary → Card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_recent_projects.default.primary.Card[].SubHeading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  SubHeading: prismic.RichTextField;

  /**
   * Label field in *OurRecentProjects → Default → Primary → Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_recent_projects.default.primary.Card[].Label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  Label: prismic.KeyTextField;

  /**
   * Name field in *OurRecentProjects → Default → Primary → Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_recent_projects.default.primary.Card[].Name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  Name: prismic.KeyTextField;

  /**
   * Location Icon field in *OurRecentProjects → Default → Primary → Card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: our_recent_projects.default.primary.Card[].LocationIcon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  LocationIcon: prismic.ImageField<never>;

  /**
   * Location Label field in *OurRecentProjects → Default → Primary → Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_recent_projects.default.primary.Card[].LocationLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  LocationLabel: prismic.KeyTextField;

  /**
   * Employee Icon field in *OurRecentProjects → Default → Primary → Card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: our_recent_projects.default.primary.Card[].EmployeeIcon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  EmployeeIcon: prismic.ImageField<never>;

  /**
   * Employee Label field in *OurRecentProjects → Default → Primary → Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_recent_projects.default.primary.Card[].EmployeeLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  EmployeeLabel: prismic.KeyTextField;

  /**
   * Setting Icon field in *OurRecentProjects → Default → Primary → Card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: our_recent_projects.default.primary.Card[].SettingIcon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  SettingIcon: prismic.ImageField<never>;

  /**
   * SettingLabel field in *OurRecentProjects → Default → Primary → Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_recent_projects.default.primary.Card[].SettingLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  SettingLabel: prismic.KeyTextField;
}

/**
 * Primary content in *OurRecentProjects → Default → Primary*
 */
export interface OurRecentProjectsSliceDefaultPrimary {
  /**
   * Title field in *OurRecentProjects → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_recent_projects.default.primary.Title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  Title: prismic.RichTextField;

  /**
   * Description field in *OurRecentProjects → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_recent_projects.default.primary.Description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  Description: prismic.RichTextField;

  /**
   * Card field in *OurRecentProjects → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: our_recent_projects.default.primary.Card[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  Card: prismic.GroupField<
    Simplify<OurRecentProjectsSliceDefaultPrimaryCardItem>
  >;
}

/**
 * Default variation for OurRecentProjects Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurRecentProjectsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OurRecentProjectsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *OurRecentProjects*
 */
type OurRecentProjectsSliceVariation = OurRecentProjectsSliceDefault;

/**
 * OurRecentProjects Shared Slice
 *
 * - **API ID**: `our_recent_projects`
 * - **Description**: OurRecentProjects
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurRecentProjectsSlice = prismic.SharedSlice<
  "our_recent_projects",
  OurRecentProjectsSliceVariation
>;

/**
 * Item in *Score → Default → Primary → Score*
 */
export interface ScoreSliceDefaultPrimaryScoreItem {
  /**
   * Heading field in *Score → Default → Primary → Score*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: score.default.primary.Score[].Heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  Heading: prismic.KeyTextField;

  /**
   * Sub Heading field in *Score → Default → Primary → Score*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: score.default.primary.Score[].SubHeading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  SubHeading: prismic.RichTextField;
}

/**
 * Primary content in *Score → Default → Primary*
 */
export interface ScoreSliceDefaultPrimary {
  /**
   * Score field in *Score → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: score.default.primary.Score[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  Score: prismic.GroupField<Simplify<ScoreSliceDefaultPrimaryScoreItem>>;
}

/**
 * Default variation for Score Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ScoreSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ScoreSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Score*
 */
type ScoreSliceVariation = ScoreSliceDefault;

/**
 * Score Shared Slice
 *
 * - **API ID**: `score`
 * - **Description**: Score
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ScoreSlice = prismic.SharedSlice<"score", ScoreSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataFooterMediaItem,
      FooterDocumentDataFooterLink1Item,
      FooterDocumentDataFooterLink2Item,
      FooterDocumentDataFooterLink3Item,
      FooterDocumentDataFooterLink4Item,
      NavbarDocument,
      NavbarDocumentData,
      NavbarDocumentDataMenusItem,
      TopNavbarDocument,
      TopNavbarDocumentData,
      TopNavbarDocumentDataTopNavbarItem,
      AllDocumentTypes,
      ContactSlice,
      ContactSliceDefaultPrimaryContactFormItem,
      ContactSliceDefaultPrimaryButtonItem,
      ContactSliceDefaultPrimary,
      ContactSliceVariation,
      ContactSliceDefault,
      FaqsSlice,
      FaqsSliceDefaultPrimaryContentItem,
      FaqsSliceDefaultPrimary,
      FaqsSliceVariation,
      FaqsSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimaryButtonItem,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HistorySlice,
      HistorySliceDefaultPrimary,
      HistorySliceVariation,
      HistorySliceDefault,
      OurBrandSlice,
      OurBrandSliceDefaultPrimary,
      OurBrandSliceVariation,
      OurBrandSliceDefault,
      OurClientsSlice,
      OurClientsSliceDefaultPrimaryOurClientsItem,
      OurClientsSliceDefaultPrimary,
      OurClientsSliceVariation,
      OurClientsSliceDefault,
      OurRecentProjectsSlice,
      OurRecentProjectsSliceDefaultPrimaryCardItem,
      OurRecentProjectsSliceDefaultPrimary,
      OurRecentProjectsSliceVariation,
      OurRecentProjectsSliceDefault,
      ScoreSlice,
      ScoreSliceDefaultPrimaryScoreItem,
      ScoreSliceDefaultPrimary,
      ScoreSliceVariation,
      ScoreSliceDefault,
    };
  }
}
