// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomeDocumentDataSlicesSlice =
  | OurBrandSlice
  | HistorySlice
  | ScoreSlice
  | HeroSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: Home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: Home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: Home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: Home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `Home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "Home", Lang>;

export type AllDocumentTypes = HomeDocument;

/**
 * Item in *Hero → Default → Primary → Button*
 */
export interface HeroSliceDefaultPrimaryButtonItem {
  /**
   * Label  field in *Hero → Default → Primary → Button*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.Button[].Label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  Label: prismic.KeyTextField;

  /**
   * Button Link field in *Hero → Default → Primary → Button*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.Button[].ButtonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  ButtonLink: prismic.LinkField;
}

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Background Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.BackgroundImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  BackgroundImage: prismic.ImageField<never>;

  /**
   * Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.Heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  Heading: prismic.KeyTextField;

  /**
   * Description field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.Description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  Description: prismic.RichTextField;

  /**
   * Button field in *Hero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.Button[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  Button: prismic.GroupField<Simplify<HeroSliceDefaultPrimaryButtonItem>>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *History → Default → Primary*
 */
export interface HistorySliceDefaultPrimary {
  /**
   * Background Image field in *History → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: history.default.primary.BackgroundImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  BackgroundImage: prismic.ImageField<never>;

  /**
   * Title field in *History → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: history.default.primary.Title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  Title: prismic.RichTextField;

  /**
   * Description field in *History → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: history.default.primary.Description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  Description: prismic.RichTextField;
}

/**
 * Default variation for History Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HistorySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HistorySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *History*
 */
type HistorySliceVariation = HistorySliceDefault;

/**
 * History Shared Slice
 *
 * - **API ID**: `history`
 * - **Description**: History
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HistorySlice = prismic.SharedSlice<
  "history",
  HistorySliceVariation
>;

/**
 * Primary content in *OurBrand → Default → Primary*
 */
export interface OurBrandSliceDefaultPrimary {
  /**
   * Title field in *OurBrand → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_brand.default.primary.Title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  Title: prismic.RichTextField;

  /**
   * Description field in *OurBrand → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_brand.default.primary.Description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  Description: prismic.RichTextField;

  /**
   * Background Image field in *OurBrand → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: our_brand.default.primary.BackgroundImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  BackgroundImage: prismic.ImageField<never>;
}

/**
 * Default variation for OurBrand Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurBrandSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OurBrandSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *OurBrand*
 */
type OurBrandSliceVariation = OurBrandSliceDefault;

/**
 * OurBrand Shared Slice
 *
 * - **API ID**: `our_brand`
 * - **Description**: OurBrand
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurBrandSlice = prismic.SharedSlice<
  "our_brand",
  OurBrandSliceVariation
>;

/**
 * Item in *Score → Default → Primary → Score*
 */
export interface ScoreSliceDefaultPrimaryScoreItem {
  /**
   * Heading field in *Score → Default → Primary → Score*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: score.default.primary.Score[].Heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  Heading: prismic.KeyTextField;

  /**
   * Sub Heading field in *Score → Default → Primary → Score*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: score.default.primary.Score[].SubHeading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  SubHeading: prismic.RichTextField;
}

/**
 * Primary content in *Score → Default → Primary*
 */
export interface ScoreSliceDefaultPrimary {
  /**
   * Score field in *Score → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: score.default.primary.Score[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  Score: prismic.GroupField<Simplify<ScoreSliceDefaultPrimaryScoreItem>>;
}

/**
 * Default variation for Score Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ScoreSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ScoreSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Score*
 */
type ScoreSliceVariation = ScoreSliceDefault;

/**
 * Score Shared Slice
 *
 * - **API ID**: `score`
 * - **Description**: Score
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ScoreSlice = prismic.SharedSlice<"score", ScoreSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      AllDocumentTypes,
      HeroSlice,
      HeroSliceDefaultPrimaryButtonItem,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HistorySlice,
      HistorySliceDefaultPrimary,
      HistorySliceVariation,
      HistorySliceDefault,
      OurBrandSlice,
      OurBrandSliceDefaultPrimary,
      OurBrandSliceVariation,
      OurBrandSliceDefault,
      ScoreSlice,
      ScoreSliceDefaultPrimaryScoreItem,
      ScoreSliceDefaultPrimary,
      ScoreSliceVariation,
      ScoreSliceDefault,
    };
  }
}
