// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  contact: dynamic(() => import("./Contact")),
  faqs: dynamic(() => import("./Faqs")),
  hero: dynamic(() => import("./Hero")),
  history: dynamic(() => import("./History")),
  menus: dynamic(() => import("./Menus")),
  our_brand: dynamic(() => import("./OurBrand")),
  our_clients: dynamic(() => import("./OurClients")),
  our_recent_projects: dynamic(() => import("./OurRecentProjects")),
  score: dynamic(() => import("./Score")),
};
