// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  history: dynamic(() => import("./History")),
  score: dynamic(() => import("./Score")),
};
